Format

diff --git a/install b/install
--- a/install
+++ b/install
@@ -3,126 +3,127 @@
 export server_user="hlds"
 
 if [[ "$(id -u)" -ne 0 ]]; then
-	echo "Run this script as root"
-	echo "Pass \"remove\" arg to uninstall"
-	exit 1
+    printf "Run this script as root\n"
+    printf "Pass \"remove\" arg to uninstall\n"
+    exit 1
 fi
 
-trap "pkill -SIGINT steamcmd > /dev/null 2>&1; echo -en \"\nInstallation aborted\n\"; exit 1" INT
+trap "pkill -SIGINT steamcmd > /dev/null 2>&1; printf \"\nInstallation aborted\n\"; exit 1" INT
 
 remove_server() {
-	if pgrep -u hlds > /dev/null 2>&1; then
-		echo "hlds user has processes running"
-		echo "Stop them before uninstalling the server"
-		exit 1
-	fi
-	userdel -r "${server_user}"
-	rm -vrf /etc/hlds
-	rm -vf /usr/bin/cs16-server
-	rm -vf /usr/share/man/man1/cs16-server.1.gz
-	[[ -x "$(command -v systemctl)" ]] && rm -vf /usr/lib/systemd/system/cs16-server.service
+    if pgrep -u hlds > /dev/null 2>&1; then
+        printf "hlds user has processes running\n"
+        printf "Stop them before uninstalling the server\n"
+        exit 1
+    fi
+    userdel -r "${server_user}"
+    rm -vrf /etc/hlds
+    rm -vf /usr/bin/cs16-server
+    rm -vf /usr/share/man/man1/cs16-server.1*
+    [[ -x "$(command -v systemctl)" ]] && rm -vf /usr/lib/systemd/system/cs16-server.service
 }
 
 check_depends() {
-	lib32_warn() {
-		echo "Install 32-bit libstdc++"
-		echo "See README.md for details"
-		exit 1
-	}
+    lib32_warn() {
+        printf "Install 32-bit libstdc++\n"
+        printf "See README.md for details\n"
+        exit 1
+    }
 
-	if [[ -x "$(command -v pacman)" ]] || [[ -x "$(command -v apt)" ]]; then
-		[[ ! -d "/usr/lib32" ]] && lib32_warn
-		find /usr/lib32 -type f | grep -q libstdc++ || lib32_warn
-	elif [[ -x "$(command -v dnf)" ]]; then
-		find /usr/lib -type f | grep -q libstdc++ || lib32_warn
-	else
-		echo "Unknown distro, make sure you have 32-bit libstdc++"
-		echo "Press Enter to continue"
-		read -r
-	fi
+    if [[ -x "$(command -v pacman)" ]] || [[ -x "$(command -v apt)" ]]; then
+        [[ ! -d "/usr/lib32" ]] && lib32_warn
+        find /usr/lib32 -type f | grep -q libstdc++ || lib32_warn
+    elif [[ -x "$(command -v dnf)" ]]; then
+        find /usr/lib -type f | grep -q libstdc++ || lib32_warn
+    else
+        printf "Unknown distro, make sure you have 32-bit libstdc++\n"
+        printf "Press Enter to continue\n"
+        read -r
+    fi
 
-	pkgs=(tar xz gzip curl)
+    pkgs=(tar xz gzip curl)
 
-	for pkg in "${pkgs[@]}"; do
-		[[ -x "$(command -v "${pkg}")" ]] || missing_pkgs="${missing_pkgs} ${pkg}"
-	done
+    for pkg in "${pkgs[@]}"; do
+        [[ -x "$(command -v "${pkg}")" ]] || missing_pkgs="${missing_pkgs} ${pkg}"
+    done
 
-	[[ -n "${missing_pkgs}" ]] && echo "Install the following packages:${missing_pkgs}" && exit 1
+    [[ -n "${missing_pkgs}" ]] && printf "Install the following packages:%s\n" "${missing_pkgs}" && exit 1
 }
 
 install_stage_one() {
-	[[ -d "/home/${server_user}" ]] && echo "Server is already installed" && exit 1
+    [[ -d "/home/${server_user}" ]] && printf "Server is already installed\n" && exit 1
 
-	useradd -m -s /usr/bin/bash "${server_user}"
-	passwd -l "${server_user}"
+    useradd -m -s /usr/bin/bash "${server_user}"
+    passwd -l "${server_user}"
 
-	mkdir -vp /tmp/cs16-server && pushd /tmp/cs16-server || exit 1
+    mkdir -vp /tmp/cs16-server && pushd /tmp/cs16-server || exit 1
 
-	links=(
-		https://steamcdn-a.akamaihd.net/client/steamcmd_linux.tar.gz
-		https://github.com/Bots-United/metamod-p/releases/download/v1.21p38/metamod_i686_linux_win32-1.21p38.tar.xz
-		https://www.amxmodx.org/amxxdrop/1.10/amxmodx-latest-base-linux.tar.gz
-		https://www.amxmodx.org/amxxdrop/1.10/amxmodx-latest-cstrike-linux.tar.gz
-		https://github.com/yapb/yapb/releases/download/4.4.957/yapb-4.4.957-linux.tar.xz
-	)
+    links=(
+        https://steamcdn-a.akamaihd.net/client/steamcmd_linux.tar.gz
+        https://github.com/Bots-United/metamod-p/releases/download/v1.21p38/metamod_i686_linux_win32-1.21p38.tar.xz
+        https://www.amxmodx.org/amxxdrop/1.10/amxmodx-latest-base-linux.tar.gz
+        https://www.amxmodx.org/amxxdrop/1.10/amxmodx-latest-cstrike-linux.tar.gz
+        https://github.com/yapb/yapb/releases/download/4.4.957/yapb-4.4.957-linux.tar.xz
+    )
 
-	for link in "${links[@]}"; do
-		echo "==> Downloading ${link}"
-		curl -fLO "${link}" || { echo "Failed to download ${link}"; exit 1; }
-	done
+    for link in "${links[@]}"; do
+        printf "==> Downloading %s\n" "${link}"
+        curl -fLO "${link}" || { printf "Failed to download %s\n" "${link}"; exit 1; }
+    done
 
-	popd || exit 1
+    popd || exit 1
 
-	install -vm 755 cs16-server/cs16-server -t /usr/bin
-	install -vDm 644 cs16-server/cs16-server.conf -t /etc/hlds
-	install -vm 644 cs16-server/cs16-server.1 -t /usr/share/man/man1
-	gzip -vf --best /usr/share/man/man1/cs16-server.1
+    install -vm 755 cs16-server/cs16-server -t /usr/bin
+    install -vDm 644 cs16-server/cs16-server.conf -t /etc/hlds
+    install -vm 644 cs16-server/cs16-server.1 -t /usr/share/man/man1
+    gzip -vf --best /usr/share/man/man1/cs16-server.1
 }
 
 install_stage_two() {
-	cd "/home/${server_user}" || exit 1
-	mkdir -vp .steam && cd .steam || exit 1
-	ln -sfv . steam
+    cd "/home/${server_user}" || exit 1
+    mkdir -vp .steam && cd .steam || exit 1
+    ln -sfv . steam
 
-	for arc in /tmp/cs16-server/*.tar.*; do
-		tar xvf "${arc}"
-	done
+    for arc in /tmp/cs16-server/*.tar.*; do
+        tar xvf "${arc}"
+    done
 
-	for _i in {1..3}; do
-		./steamcmd.sh +force_install_dir cs16 +login anonymous +app_update 90 validate +quit
-	done
+    for _i in {1..3}; do
+        ./steamcmd.sh +force_install_dir cs16 +login anonymous +app_update 90 validate +quit
+    done
 
-	# Temporary fix for 4.4.957
-	chmod -v 755 addons/yapb/data/*
+    # Temporary fix for 4.4.957
+    chmod -v 755 addons/yapb/data/*
 
-	mv -vf addons cs16/cstrike
+    mv -vf addons cs16/cstrike
 
-	mkdir -vp cs16/cstrike/addons/metamod/dlls
-	mv -vf metamod.so cs16/cstrike/addons/metamod/dlls
-	rm -vf metamod.dll
+    mkdir -vp cs16/cstrike/addons/metamod/dlls
+    mv -vf metamod.so cs16/cstrike/addons/metamod/dlls
+    rm -vf metamod.dll
 
-	echo "linux addons/amxmodx/dlls/amxmodx_mm_i386.so" > cs16/cstrike/addons/metamod/plugins.ini
-	echo ";;linux addons/yapb/bin/yapb.so" >> cs16/cstrike/addons/metamod/plugins.ini
+    printf "linux addons/amxmodx/dlls/amxmodx_mm_i386.so\n" > cs16/cstrike/addons/metamod/plugins.ini
+    printf ";;linux addons/yapb/bin/yapb.so\n" >> cs16/cstrike/addons/metamod/plugins.ini
 
-	ln -sfv linux32 sdk32
-	touch cs16/cstrike/{listip.cfg,banned.cfg}
+    ln -sfv linux32 sdk32
+    touch cs16/cstrike/{listip.cfg,banned.cfg}
 }
 
 install_service() {
-	install -m 644 cs16-server/cs16-server.service -t /usr/lib/systemd/system
-	echo -en "\nRun \"systemctl enable cs16-server\" to start server on boot"
+    install -m 644 cs16-server/cs16-server.service -t /usr/lib/systemd/system
+    printf "\nRun \"systemctl enable cs16-server\" to start server on boot"
 }
 
 case "$1" in
-	remove)
-		remove_server
-		;;
-	"")
-		check_depends
-		install_stage_one
-		su "${server_user}" -c "$(declare -f install_stage_two); install_stage_two"
-		[[ -x "$(command -v systemctl)" ]] && install_service
-		echo -en "\nhlds parameters can be set in /etc/hlds/cs16-server.conf\n"
-		echo -en "\nInstallation completed\n\n"
-		;;
+    remove)
+            remove_server
+         ;;
+
+        "")
+            check_depends
+            install_stage_one
+            su "${server_user}" -c "$(declare -f install_stage_two); install_stage_two"
+            [[ -x "$(command -v systemctl)" ]] && install_service
+            printf "\nhlds parameters can be set in /etc/hlds/cs16-server.conf\n"
+            printf "\nInstallation completed\n\n"
+         ;;
 esac
