Big update

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,135 +1,132 @@
-#!/bin/sh
+#!/bin/bash
+
+export server_user=hlds
 
 if [ "$(id -u)" -ne 0 ]; then
-	printf '\nRun this script as root'
-	printf '\nPass remove arg to uninstall\n\n'
+	echo 'Run this script as root'
+	echo 'Pass "remove" arg to uninstall'
 	exit 1
 fi
 
-server_user=hlds
+trap 'killall -s SIGINT steamcmd > /dev/null 2>&1; echo -en "\nInstallation aborted\n"; exit 1' INT
 
-if [ "$1" = remove ]; then
-	if [ -n "$(pgrep hlds)" ]; then
-		printf 'Server is running\n'
-		printf 'Stop it before uninstalling it\n'
+remove_server() {
+	if pgrep hlds > /dev/null 2>&1; then
+		echo 'Server is running'
+		echo 'Stop it before uninstalling'
 		exit 1
 	fi
-	rm -vrf /home/${server_user:?}
+	rm -vrf "/home/${server_user:?}"
 	rm -vrf /etc/hlds
-	rm -vf /var/spool/mail/${server_user}
-	rm -vf /usr/share/man/man1/cs16-server.1.gz
 	rm -vf /usr/bin/cs16-server
-	if [ -n "$(command -v systemctl)" ]; then
-		rm -vf /usr/lib/systemd/system/cs16-server.service
-	elif [ -n "$(command -v openrc-run)" ]; then
-		rm -vf /etc/init.d/cs16-server
-	fi
-	userdel -f $server_user
+	rm -vf /usr/share/man/man1/cs16-server.1.gz
+	rm -vf "/var/spool/mail/$server_user"
+	[ -x "$(command -v systemctl)" ] && rm -vf /usr/lib/systemd/system/cs16-server.service
+	[ -x "$(command -v openrc-run)" ] && rm -vf /etc/init.d/cs16-server
+	userdel -f "$server_user"
 	exit 0
-elif [ -n "$1" ]; then
-	exit 1
-fi
-
-grep -q "^$server_user" /etc/passwd && printf "\nServer is already installed\n\n" && exit 1
-
-ctrl_c() {
-	killall -s SIGINT steamcmd > /dev/null 2>&1
-	printf '\n\nInstallation aborted\n\n'
-	exit 1
 }
 
-trap ctrl_c INT
+check_depends() {
+	lib32_warn() {
+		echo 'Install 32-bit libstdc++'
+		echo 'See README.md for details'
+		exit 1
+	}
 
-lib32_warn() {
-	printf '\nInstall 32 bit libstdc++\n'
-	printf 'README.md for more info\n\n'
-	exit 1
-}
+	if [ -x "$(command -v pacman)" ] || [ -x "$(command -v apt)" ]; then
+		[ ! -d /usr/lib32 ] && lib32_warn
+		find /usr/lib32 -type f | grep -q libstdc++ || lib32_warn
+	elif [ -x "$(command -v dnf)" ]; then
+		find /usr/lib -type f | grep -q libstdc++ || lib32_warn
+	else
+		echo 'Unknown distro, make sure you have 32-bit libstdc++'
+		echo 'Press Enter to continue'
+		read -r
+	fi
 
-if [ -n "$(command -v pacman)" ] || [ -n "$(command -v apt)" ]; then
-	if [ ! -d /usr/lib32 ] || [ "$(find /usr/lib32 -type f | grep libstdc++)" = "" ]; then
-		lib32_warn
-	fi
-elif [ -n "$(command -v dnf)" ]; then
-	if [ "$(find /usr/lib -type f | grep libstdc++)" = "" ]; then
-		lib32_warn
-	fi
-else
-	stty -echo
-	printf '\nUnknown distro, make sure you have 32 bit libstdc++\n'
-	printf 'Press Enter to continue\n'
-	while IFS= read -r line; do
-		if [ -z "$line" ]; then
-			break
-		fi
+	pkgs=(tar xz gzip curl)
+
+	for pkg in "${pkgs[@]}"; do
+		[ -x "$(command -v "$pkg")" ] || missing_packages="$missing_packages $pkg"
 	done
-	stty echo
-fi
 
-set -- tar xz gzip curl
+	[ -n "$missing_packages" ] && echo "Install the following packages:$missing_packages" && exit 1
+}
 
-for pkg in "$@"; do
-	if  [ -z "$(command -v "$pkg")" ]; then
-		to_install="$to_install $pkg"
-	fi
-done
+install_stage_one() {
+	[ -d "/home/$server_user" ] && echo 'Server already installed' && exit 1
 
-if [ -n "$to_install" ]; then
-	printf '\nInstall%s\n\n' "$to_install"
-	exit 1
-fi
+	useradd -m -s /usr/bin/bash "$server_user"
+	passwd -l "$server_user"
 
-set -- \
-https://steamcdn-a.akamaihd.net/client/steamcmd_linux.tar.gz \
-https://github.com/Bots-United/metamod-p/releases/download/v1.21p38/metamod_i686_linux_win32-1.21p38.tar.xz \
-https://www.amxmodx.org/amxxdrop/1.10/amxmodx-latest-base-linux.tar.gz \
-https://www.amxmodx.org/amxxdrop/1.10/amxmodx-latest-cstrike-linux.tar.gz \
-https://github.com/yapb/yapb/releases/download/4.4.957/yapb-4.4.957-linux.tar.xz
+	mkdir -vp /tmp/cs16-server && pushd /tmp/cs16-server || exit 1
 
-git_dir=$(pwd)
+	links=(
+		https://steamcdn-a.akamaihd.net/client/steamcmd_linux.tar.gz
+		https://github.com/Bots-United/metamod-p/releases/download/v1.21p38/metamod_i686_linux_win32-1.21p38.tar.xz
+		https://www.amxmodx.org/amxxdrop/1.10/amxmodx-latest-base-linux.tar.gz
+		https://www.amxmodx.org/amxxdrop/1.10/amxmodx-latest-cstrike-linux.tar.gz
+		https://github.com/yapb/yapb/releases/download/4.4.957/yapb-4.4.957-linux.tar.xz
+	)
 
-mkdir -vm 755 /tmp/cs16-server
-cd /tmp/cs16-server || exit
+	for link in "${links[@]}"; do
+		echo "==> Downloading $link"
+		curl -fLO "$link" || { echo "Failed to download $link"; exit 1; }
+	done
 
-for link in "$@"; do
-	printf "==> Downloading %s\n" "$link"
-	curl -fLO "$link" && continue
-	printf "Failed to download %s\n" "$link"
-	exit 1
-done
+	popd || exit 1
 
-cd "$git_dir" || exit
+	install -vm 755 cs16-server/cs16-server -t /usr/bin
+	install -vDm 644 cs16-server/cs16-server.conf -t /etc/hlds
+	install -vm 644 man/cs16-server.1.gz -t /usr/share/man/man1
+}
 
-chmod -v 644 /tmp/cs16-server/*
+install_stage_two() {
+	cd "/home/$server_user" || exit 1
+	mkdir -vp .steam && cd .steam || exit 1
+	ln -sfv . steam
 
-useradd -m -s /usr/bin/sh $server_user
-chmod 700 /home/$server_user
-passwd -l $server_user
+	for arc in /tmp/cs16-server/*.tar.*; do
+		tar xvf "$arc"
+	done
 
-install -vm 755 cs16-server/cs16-server -t /usr/bin
-install -vDm 644 cs16-server/cs16-server.conf -t /etc/hlds
-install -vm 644 man/cs16-server.1.gz -t /usr/share/man/man1
+	mkdir -vp cs16/cstrike/addons/metamod/dlls
+	mv -v metamod.* cs16/cstrike/addons/metamod/dlls
+	echo 'linux addons/amxmodx/dlls/amxmodx_mm_i386.so' > cs16/cstrike/addons/metamod/plugins.ini
+	echo ';;linux addons/yapb/bin/yapb.so' >> cs16/cstrike/addons/metamod/plugins.ini
 
-cp -vf install-stage-two /tmp/install-stage-two
-chmod -v 755 /tmp/install-stage-two
+	for _i in {1..3}; do
+		./steamcmd.sh +force_install_dir cs16 +login anonymous +app_update 90 validate +quit
+	done
 
-su $server_user -c /tmp/install-stage-two
+	ln -sfv linux32 sdk32
+	touch cs16/cstrike/{listip.cfg,banned.cfg}
+}
 
-if [ -f "/home/$server_user/.steam/cs16/cstrike/banned.cfg" ]; then
-	if [ -n "$(command -v systemctl)" ]; then
-		if [ -n "$(command -v sestatus)" ]; then
-			install -vm 644 service/selinux/systemd/cs16-server.service -t /usr/lib/systemd/system
+install_services() {
+	if [ -x "$(command -v systemctl)" ]; then
+		if [ -x "$(command -v sestatus)" ]; then
+			install -m 644 service/selinux/systemd/cs16-server.service -t /usr/lib/systemd/system
 		else
-			install -vm 644 service/systemd/cs16-server.service -t /usr/lib/systemd/system
+			install -m 644 service/systemd/cs16-server.service -t /usr/lib/systemd/system
 		fi
-		printf '\nRun systemctl enable cs16-server to start server on boot'
-	elif [ -n "$(command -v openrc-run)" ]; then
-		if [ -n "$(command -v sestatus)" ]; then
-			install -vm 755 service/selinux/openrc/cs16-server -t /etc/init.d
+		echo -en '\nRun "systemctl enable cs16-server" to start server on boot'
+	elif [ -x "$(command -v openrc-run)" ]; then
+		if [ -x "$(command -v sestatus)" ]; then
+			install -m 755 service/selinux/openrc/cs16-server -t /etc/init.d
 		else
-			install -vm 755 service/openrc/cs16-server -t /etc/init.d
+			install -m 755 service/openrc/cs16-server -t /etc/init.d
 		fi
-		printf '\nRun rc-update add cs16-server to start server on boot'
+		echo -en '\nRun "rc-update add cs16-server" to start server on boot'
 	fi
-	printf '\nInstallation completed\n\n'
-fi
+	echo -en '\nInstallation completed\n\n'
+}
+
+case $1 in
+	remove) remove_server;;
+	"") check_depends
+	    install_stage_one
+	    su "$server_user" -c "$(declare -f install_stage_two); install_stage_two"
+	    [ -f "/home/$server_user/.steam/cs16/cstrike/banned.cfg" ] && install_services;;
+esac
