Fixes

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-set -e
+set -euo pipefail
 
 if [[ "$(id -u)" -ne 0 ]]; then
     printf "This script must be run as root\n"
@@ -10,7 +10,7 @@ fi
 
 export server_user="hlds"
 
-trap "pkill -SIGINT steamcmd > /dev/null 2>&1; printf \"\nInstallation aborted\n\"; exit 1" INT
+trap "pkill -SIGINT steamcmd > /dev/null 2>&1; printf \"\nInstallation aborted\n\"; exit 1" INT ERR
 
 remove_server() {
     if pgrep -u "${server_user}" > /dev/null 2>&1; then
