Update SIGINT trap

diff --git a/install b/install
--- a/install
+++ b/install
@@ -8,7 +8,7 @@ if [ "$(id -u)" -ne 0 ]; then
 	exit 1
 fi
 
-trap 'killall -s SIGINT steamcmd > /dev/null 2>&1; echo -en "\nInstallation aborted\n"; exit 1' INT
+trap 'pkill -SIGINT steamcmd > /dev/null 2>&1; echo -en "\nInstallation aborted\n"; exit 1' INT
 
 remove_server() {
 	if pgrep hlds > /dev/null 2>&1; then
