Update scripts

diff --git a/extra/install-maps-and-graphs b/extra/install-maps-and-graphs
--- a/extra/install-maps-and-graphs
+++ b/extra/install-maps-and-graphs
@@ -4,7 +4,10 @@
 
 server_user="hlds"
 
-[[ "$(id -un)" == "${server_user}" ]] || { printf "You must run this script as %s user\n" "${server_user}"; exit 1; }
+if [[ "$(id -un)" != "${server_user}" ]]; then
+    printf "You must run this script as %s user\n" "${server_user}"
+    exit 1
+fi
 
 trap "printf \"\n\nInstallation aborted\n\n\"; exit 1" INT
 
@@ -15,17 +18,24 @@ check_depends() {
         [[ -x "$(command -v "${pkg}")" ]] || missing_pkgs="${missing_pkgs} ${pkg}"
     done
 
-    [[ -n "${missing_pkgs}" ]] && printf "Install the following packages:%s\n" "${missing_pkgs}" && exit 1
+    if [[ -n "${missing_pkgs}" ]]; then
+        printf "Install the following packages:%s\n" "${missing_pkgs}"
+        exit 1
+    fi
 }
 
 download_files() {
     cd "/home/${server_user}" || exit 1
-    mkdir -v cs16-maps-and-graphs
+    mkdir -vp cs16-maps-and-graphs
     cd cs16-maps-and-graphs || exit 1
 
     printf "==> Downloading map pack, it is going to take some time\n"
     map_link="https://archive.org/download/cs-1.6-mega-map-pack-v-2018.1.7z/CS%201.6%20Mega%20Map%20Pack%20v2018.1.7z"
-    curl -fLO "${map_link}" -o cs-1.6-mega-map-pack-v-2018.1.7z || { printf "Failed to download map archive\n"; exit 1; }
+
+    if ! curl -fLO "${map_link}" -o cs-1.6-mega-map-pack-v-2018.1.7z; then
+        printf "Failed to download map archive\n"
+        exit 1
+    fi
 
     git clone https://github.com/yapb/graph
 }
diff --git a/install b/install
--- a/install
+++ b/install
@@ -34,9 +34,9 @@ check_depends() {
 
     if [[ -x "$(command -v pacman)" ]] || [[ -x "$(command -v apt)" ]]; then
         [[ ! -d "/usr/lib32" ]] && lib32_warn
-        find /usr/lib32 -type f | grep -q libstdc++ || lib32_warn
+        find /usr/lib32 -type f | grep -q libstdc++.so || lib32_warn
     elif [[ -x "$(command -v dnf)" ]]; then
-        find /usr/lib -type f | grep -q libstdc++ || lib32_warn
+        find /usr/lib -type f | grep -q libstdc++.so || lib32_warn
     else
         printf "Unknown distro, make sure you have 32-bit libstdc++\n"
         printf "Press Enter to continue\n"
@@ -56,7 +56,10 @@ check_depends() {
 }
 
 install_stage_one() {
-    [[ -d "/home/${server_user}" ]] && printf "Server is already installed\n" && exit 1
+    if [[ -d "/home/${server_user}" ]]; then
+        printf "Server is already installed\n"
+        exit 1
+    fi
 
     useradd -m -s /usr/bin/bash "${server_user}"
     passwd -l "${server_user}"
@@ -73,7 +76,10 @@ install_stage_one() {
 
     for link in "${links[@]}"; do
         printf "==> Downloading %s\n" "${link}"
-        curl -fLO "${link}" || { printf "Failed to download %s\n" "${link}"; exit 1; }
+        if ! curl -fLO "${link}"; then
+            printf "Failed to download %s\n" "${link}"
+            exit 1
+        fi
     done
 
     popd || exit 1
