Update scripts

diff --git a/extra/install-maps-and-graphs b/extra/install-maps-and-graphs
--- a/extra/install-maps-and-graphs
+++ b/extra/install-maps-and-graphs
@@ -1,46 +1,43 @@
-#!/bin/sh
+#!/bin/bash
+
+# Copy this script to /home/hlds directory and run it as hlds user
 
 server_user=hlds
 
-if [ "$(id -un)" != "$server_user" ]; then
-	printf 'You must run this as %s user\n' "$server_user"
-	exit 1
-fi
+[ "$(id -un)" = "$server_user" ] || { echo "You must run this script as $server_user user"; exit 1; }
 
-ctrl_c() {
-	printf '\n\nInstallation aborted\n\n'
-	exit 1
+trap 'echo -en "\n\nInstallation aborted\n\n"; exit 1' INT
+
+check_depends() {
+	pkgs=(git 7z curl)
+
+	for pkg in "${pkgs[@]}"; do
+		[ -x "$(command -v "$pkg")" ] || missing_pkgs="$missing_pkgs $pkg"
+	done
+
+	[ -n "$missing_pkgs" ] && echo "Install the following packages:$missing_pkgs" && exit 1
 }
 
-trap ctrl_c INT
+download_files() {
+	cd "/home/$server_user" || exit 1
+	mkdir -v cs16-maps-and-graphs
+	cd cs16-maps-and-graphs || exit 1
 
-set -- git 7z curl
+	echo '==> Downloading map pack, it is going to take some time'
+	map_link='https://archive.org/download/cs-1.6-mega-map-pack-v-2018.1.7z/CS%201.6%20Mega%20Map%20Pack%20v2018.1.7z'
+	curl -fLO "$map_link" -o cs-1.6-mega-map-pack-v-2018.1.7z || { echo 'Failed to download map archive'; exit 1; }
 
-for pkg in "$@"; do
-	if  [ -z "$(command -v "$pkg")" ]; then
-		to_install="$to_install $pkg"
-	fi
-done
+	git clone https://github.com/yapb/graph
+}
 
-if [ -n "$to_install" ]; then
-	printf '\nInstall%s\n\n' "$to_install"
-	exit 1
-fi
+copy_files() {
+	7z x -o"/home/$server_user/.steam/cs16" cs-1.6-mega-map-pack-v-2018.1.7z
+	cp -v graph/graph/* "/home/$server_user/.steam/cs16/cstrike/addons/yapb/data/graph"
+}
 
-cd "/home/$server_user" || exit
-mkdir -v cs16-maps-and-graphs
-cd cs16-maps-and-graphs || exit
 
-printf '==> Downloading map pack, it is going to take some time\n'
-
-if ! curl -fL 'https://archive.org/download/cs-1.6-mega-map-pack-v-2018.1.7z/CS%201.6%20Mega%20Map%20Pack%20v2018.1.7z' -o cs-1.6-mega-map-pack-v-2018.1.7z; then
-	printf 'Failed to download archive\n'
-	exit 1
-fi
-
-git clone https://github.com/yapb/graph
-
-7z x -o"/home/$server_user/.steam/cs16" cs-1.6-mega-map-pack-v-2018.1.7z
-cp -v graph/graph/* "/home/$server_user/.steam/cs16/cstrike/addons/yapb/data/graph"
-
-printf '\nInstallation completed\n\n'
+case $1 in
+	"")
+		check_depends; download_files; copy_files
+		echo -en '\nInstallation completed\n\n';;
+esac
