Add missing ] and use printf instead of echo

diff --git a/extra/install-maps-and-graphs b/extra/install-maps-and-graphs
--- a/extra/install-maps-and-graphs
+++ b/extra/install-maps-and-graphs
@@ -4,9 +4,9 @@
 
 server_user="hlds"
 
-[[ "$(id -un)" == "${server_user}" ]] || { echo "You must run this script as ${server_user} user"; exit 1; }
+[[ "$(id -un)" == "${server_user}" ]] || { printf "You must run this script as %s user\n" "${server_user}"; exit 1; }
 
-trap "echo -en \"\n\nInstallation aborted\n\n\"; exit 1" INT
+trap "printf \"\n\nInstallation aborted\n\n\"; exit 1" INT
 
 check_depends() {
     pkgs=("git" "7z" "curl")
@@ -15,7 +15,7 @@ check_depends() {
         [[ -x "$(command -v "${pkg}")" ]] || missing_pkgs="${missing_pkgs} ${pkg}"
     done
 
-    [[ -n "${missing_pkgs}" ] && echo "Install the following packages:${missing_pkgs}" && exit 1
+    [[ -n "${missing_pkgs}" ]] && printf "Install the following packages:%s\n" "${missing_pkgs}" && exit 1
 }
 
 download_files() {
@@ -23,9 +23,9 @@ download_files() {
     mkdir -v cs16-maps-and-graphs
     cd cs16-maps-and-graphs || exit 1
 
-    echo "==> Downloading map pack, it is going to take some time"
+    printf "==> Downloading map pack, it is going to take some time\n"
     map_link="https://archive.org/download/cs-1.6-mega-map-pack-v-2018.1.7z/CS%201.6%20Mega%20Map%20Pack%20v2018.1.7z"
-    curl -fLO "${map_link}" -o cs-1.6-mega-map-pack-v-2018.1.7z || { echo "Failed to download map archive"; exit 1; }
+    curl -fLO "${map_link}" -o cs-1.6-mega-map-pack-v-2018.1.7z || { printf "Failed to download map archive\n"; exit 1; }
 
     git clone https://github.com/yapb/graph
 }
@@ -40,6 +40,6 @@ case "$1" in
         check_depends
         download_files
         copy_files
-        echo -en "\nInstallation completed\n\n"
+        printf "\nInstallation completed\n\n"
         ;;
 esac
