Only check for config

diff --git a/cs16-server/cs16-server b/cs16-server/cs16-server
--- a/cs16-server/cs16-server
+++ b/cs16-server/cs16-server
@@ -11,23 +11,6 @@ server_user="hlds"
 server_conf="/etc/hlds/cs16-server.conf"
 server_workdir="/home/${server_user}/.steam"
 
-_check_pre_start() {
-    if [[ ! -f "${server_conf}" ]]; then
-        printf "Error: Configuration file %s not found\n" "${server_conf}"
-        exit 1
-    elif [[ ! -x "${server_workdir}/cs16/hlds_run" ]]; then
-        printf "Error: Required file %s not found/executable\n" "${server_workdir}/cs16/hlds_run"
-        exit 1
-    fi
-}
-
-_check_pre_update() {
-    if [[ ! -x "${server_workdir}/steamcmd.sh" ]]; then
-        printf "Error: Required file %s not found/executable\n" "${server_workdir}/steamcmd.sh"
-        exit 1
-    fi
-}
-
 _is_server_running() {
     pgrep -u "${server_user}" hlds_ &> /dev/null
 }
@@ -37,6 +20,10 @@ _is_server_updating() {
 }
 
 _start_hlds() {
+    if [[ ! -f "${server_conf}" ]]; then
+        printf "Error: Configuration file %s not found\n" "${server_conf}"
+        exit 1
+    fi
     source "${server_conf}"
     su "${server_user}" -c "cd ${server_workdir}/cs16 && \
         ./hlds_run ${server_game:-} ${server_params:-} ${server_dll:-} &> /dev/null &"
@@ -64,7 +51,6 @@ _update_hlds() {
 }
 
 start_server() {
-    _check_pre_start
     if _is_server_updating; then
         printf "Server is being updated, wait for it to finish\n"
         exit 1
@@ -89,7 +75,6 @@ stop_server() {
 }
 
 restart_server() {
-    _check_pre_start
     if _is_server_updating; then
         printf "Server is being updated, wait for it to finish\n"
         exit 1
@@ -103,7 +88,6 @@ restart_server() {
 }
 
 update_server() {
-    _check_pre_update
     if _is_server_updating; then
         printf "Server is already being updated, wait for it to finish\n"
         exit 1
