scripts: >&2 -> 1>&2

diff --git a/cs16-server/cs16-server b/cs16-server/cs16-server
--- a/cs16-server/cs16-server
+++ b/cs16-server/cs16-server
@@ -5,7 +5,7 @@ set -euo pipefail
 progname="${0##*/}"
 
 if [[ "$(id -u)" -ne 0 ]]; then
-    printf "%s requires root privileges\n" "${progname}" >&2
+    printf "%s requires root privileges\n" "${progname}" 1>&2
     exit 1
 fi
 
@@ -23,7 +23,7 @@ _is_server_updating() {
 
 _start_hlds() {
     if [[ ! -f "${server_conf}" ]]; then
-        printf "Error: Configuration file %s not found\n" "${server_conf}" >&2
+        printf "Error: Configuration file %s not found\n" "${server_conf}" 1>&2
         exit 1
     fi
     eval "$(grep server_params "${server_conf}")"
@@ -42,7 +42,7 @@ _kill_hlds() {
         sleep 1
     done
     runuser -u "${server_user}" -- /bin/bash -c "pkill -u ${server_user} -SIGTERM hlds_"
-    printf "Warning: Server was forcefully terminated\n" >&2
+    printf "Warning: Server was forcefully terminated\n" 1>&2
 }
 
 _update_hlds() {
@@ -51,10 +51,10 @@ _update_hlds() {
 
 start_server() {
     if _is_server_updating; then
-        printf "Server is being updated, wait for it to finish\n" >&2
+        printf "Server is being updated, wait for it to finish\n" 1>&2
         exit 1
     elif _is_server_running; then
-        printf "Server is already running\n" >&2
+        printf "Server is already running\n" 1>&2
         exit 1
     fi
     printf "Starting server\n"
@@ -63,10 +63,10 @@ start_server() {
 
 stop_server() {
     if _is_server_updating; then
-        printf "Server is being updated, wait for it to finish\n" >&2
+        printf "Server is being updated, wait for it to finish\n" 1>&2
         exit 1
     elif ! _is_server_running; then
-        printf "Server is not running\n" >&2
+        printf "Server is not running\n" 1>&2
         exit 1
     fi
     printf "Stopping server\n"
@@ -75,7 +75,7 @@ stop_server() {
 
 restart_server() {
     if _is_server_updating; then
-        printf "Server is being updated, wait for it to finish\n" >&2
+        printf "Server is being updated, wait for it to finish\n" 1>&2
         exit 1
     elif _is_server_running; then
         printf "Restarting server\n"
@@ -88,10 +88,10 @@ restart_server() {
 
 update_server() {
     if _is_server_updating; then
-        printf "Server is already being updated, wait for it to finish\n" >&2
+        printf "Server is already being updated, wait for it to finish\n" 1>&2
         exit 1
     elif _is_server_running; then
-        printf "Server is running, stop it first\n" >&2
+        printf "Server is running, stop it first\n" 1>&2
         exit 1
     fi
     printf "Updating server\n"
@@ -121,7 +121,7 @@ print_help() {
 }
 
 if [[ "${#}" -gt 1 ]]; then
-    printf "Only 1 command is accepted\n" >&2
+    printf "Only 1 command is accepted\n" 1>&2
     print_help
     exit 1
 elif [[ "${#}" -eq 0 ]]; then
@@ -146,7 +146,7 @@ case "${1}" in
         status_server
         ;;
     *)
-        printf "Invalid command: %s\n" "${1}" >&2
+        printf "Invalid command: %s\n" "${1}" 1>&2
         print_help
         exit 1
         ;;
diff --git a/extra/install-maps-and-graphs b/extra/install-maps-and-graphs
--- a/extra/install-maps-and-graphs
+++ b/extra/install-maps-and-graphs
@@ -9,12 +9,12 @@ home_dir="/var/${server_user}"
 arc="cs-1.6-mega-map-pack-v-2018.1.7z"
 
 if [[ "$(id -un)" != "${server_user}" ]]; then
-    printf "You must run this script as %s user\n" "${server_user}" >&2
+    printf "You must run this script as %s user\n" "${server_user}" 1>&2
     exit 1
 fi
 
 abort_install() {
-    printf "\nInstallation aborted\n" >&2
+    printf "\nInstallation aborted\n" 1>&2
     exit 1
 }
 
@@ -29,7 +29,7 @@ check_depends() {
     done
 
     if [[ -n "${missing_pkgs}" ]]; then
-        printf "Install the following packages:%s\n" "${missing_pkgs}" >&2
+        printf "Install the following packages:%s\n" "${missing_pkgs}" 1>&2
         exit 1
     fi
 }
