cs16-server: stderr redirects

diff --git a/cs16-server/cs16-server b/cs16-server/cs16-server
--- a/cs16-server/cs16-server
+++ b/cs16-server/cs16-server
@@ -21,7 +21,7 @@ _is_server_updating() {
 
 _start_hlds() {
     if [[ ! -f "${server_conf}" ]]; then
-        printf "Error: Configuration file %s not found\n" "${server_conf}"
+        printf "Error: Configuration file %s not found\n" "${server_conf}" >&2
         exit 1
     fi
     eval "$(grep server_params "${server_conf}")"
@@ -40,7 +40,7 @@ _kill_hlds() {
         sleep 1
     done
     runuser -u "${server_user}" -- /bin/bash -c "pkill -u ${server_user} -SIGTERM hlds_"
-    printf "Warning: Server was forcefully terminated\n"
+    printf "Warning: Server was forcefully terminated\n" >&2
 }
 
 _update_hlds() {
@@ -49,10 +49,10 @@ _update_hlds() {
 
 start_server() {
     if _is_server_updating; then
-        printf "Server is being updated, wait for it to finish\n"
+        printf "Server is being updated, wait for it to finish\n" >&2
         exit 1
     elif _is_server_running; then
-        printf "Server is already running\n"
+        printf "Server is already running\n" >&2
         exit 1
     fi
     printf "Starting server\n"
@@ -61,10 +61,10 @@ start_server() {
 
 stop_server() {
     if _is_server_updating; then
-        printf "Server is being updated, wait for it to finish\n"
+        printf "Server is being updated, wait for it to finish\n" >&2
         exit 1
     elif ! _is_server_running; then
-        printf "Server is not running\n"
+        printf "Server is not running\n" >&2
         exit 1
     fi
     printf "Stopping server\n"
@@ -73,7 +73,7 @@ stop_server() {
 
 restart_server() {
     if _is_server_updating; then
-        printf "Server is being updated, wait for it to finish\n"
+        printf "Server is being updated, wait for it to finish\n" >&2
         exit 1
     elif _is_server_running; then
         printf "Restarting server\n"
@@ -86,10 +86,10 @@ restart_server() {
 
 update_server() {
     if _is_server_updating; then
-        printf "Server is already being updated, wait for it to finish\n"
+        printf "Server is already being updated, wait for it to finish\n" >&2
         exit 1
     elif _is_server_running; then
-        printf "Server is running, stop it first\n"
+        printf "Server is running, stop it first\n" >&2
         exit 1
     fi
     printf "Updating server\n"
@@ -138,7 +138,7 @@ case "${1:-}" in
         print_help
         ;;
     *)
-        printf "Invalid command: %s\n" "${1}"
+        printf "Invalid command: %s\n" "${1}" >&2
         print_help
         exit 1
         ;;
diff --git a/install b/install
--- a/install
+++ b/install
@@ -15,7 +15,7 @@ service_dir="/usr/lib/systemd/system"
 
 abort_install() {
     pgrep steamcmd &> /dev/null && pkill -SIGINT steamcmd &> /dev/null
-    printf "\nInstallation aborted\n"
+    printf "\nInstallation aborted\n" >&2
     exit 1
 }
 
@@ -23,11 +23,11 @@ trap abort_install SIGINT
 
 remove_server() {
     if [[ ! -d "${home_dir}" ]]; then
-        printf "Server isn't installed\n"
+        printf "Server isn't installed\n" >&2
         exit 1
     elif [[ -n "$(pgrep -u "${server_user}")" ]]; then
-        printf "%s user has processes running\n" "${server_user}"
-        printf "Stop them before uninstalling the server\n"
+        printf "%s user has processes running\n" "${server_user}" >&2
+        printf "Stop them before uninstalling the server\n" >&2
         exit 1
     fi
 
@@ -42,8 +42,8 @@ remove_server() {
 
 check_depends() {
     if ! grep -q 'libstdc++.so.6 (libc6)' < <(ldconfig -p); then
-        printf "Install 32-bit libstdc++\n"
-        printf "See README.md for details\n"
+        printf "Install 32-bit libstdc++\n" >&2
+        printf "See README.md for details\n" >&2
         exit 1
     fi
 
@@ -59,14 +59,14 @@ check_depends() {
     fi
 
     if [[ -n "${missing_pkgs}" ]]; then
-        printf "Install the following packages:%s\n" "${missing_pkgs}"
+        printf "Install the following packages:%s\n" "${missing_pkgs}" >&2
         exit 1
     fi
 }
 
 install_stage_one() {
     if [[ -d "${home_dir}" ]]; then
-        printf "Server is already installed\n"
+        printf "Server is already installed\n" >&2
         exit 1
     fi
 
@@ -86,7 +86,7 @@ install_stage_one() {
     for link in "${links[@]}"; do
         printf "==> Downloading %s\n" "${link}"
         if ! curl -fLO "${link}"; then
-            printf "Failed to download %s\n" "${link}"
+            printf "Failed to download %s\n" "${link}" >&2
             exit 1
         fi
     done
